### ISSUE TITLE
Not able to connect after allowing permissions (but have confirmation of permission granted

### ISSUE THREAD

**Issue by PhilippeH1967** [microsoftgraph/python-sample-console-app#9]
Traceback (most recent call last):
  File "/python-sample-console-app/sample.py", line 81, in <module>
    GRAPH_SESSION = device_flow_session(config.CLIENT_ID)
  File "/python-sample-console-app/helpers.py", line 54, in device_flow_session
    client_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/adal/authentication_context.py", line 299, in acquire_token_with_device_code
    return self._acquire_token(token_func, user_code_info.get('correlation_id', None))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/adal/authentication_context.py", line 292, in token_func
    token = token_request.get_token_with_device_code(user_code_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/adal/token_request.py", line 392, in get_token_with_device_code
    token = client.get_token_with_polling(oauth_parameters, interval, expires_in)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/adal/oauth2_client.py", line 362, in get_token_with_polling
    wire_response)
adal.adal_error.AdalError: Unexpected polling state invalid_client

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
